name: cypress Test
on: [push]
jobs: 
  cypress-run:
       runs-on: window-latest
       steps:
         - name: Checkout
           uses: actions/checkout@v.2.3.4
         - name: Cypress.io
           uses: cypress-io/github-action@v5.6.
           with: 
             start: npm start
           
